server:
  port: 8081
spring:
  mail:
    host: live.smtp.mailtrap.io
    port: 2525
    username: api
    password: ${mailPassword:fallback}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import:
      env.properties
  jpa:
    open-in-view: false
    hibernate:
      #      ddl-auto: update
      ddl-auto: create-drop
      show-sql: false
      dialect: org.hibernate.dialect.SQLServer2012Dialect
---
spring:
  datasource:
    url: ${prodDBUrl:fallback}
    username: ${prodDBUsername:fallback}
    password: ${prodDBPassword:fallback}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
jwt:
  secret-key: ${jwtSecretKey:fallback}
  # 24 Hours
  ttl-ms: 86400000
