server:
  port: 8081
spring:
  jpa:
    open-in-view: false
    hibernate:
      #      ddl-auto: update
      ddl-auto: create-drop
      show-sql: false
---
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
jwt:
  secret-key: 03c46c509473f4a3e43653b0aac9c5682151cdc1fc6f0243a07e8739f41afd43
  # 24 Hours
  ttl-ms: 86400000
sample:
  greeting: ${SAMPLEGREETING:Hello There!}
