server:
  tomcat:
    max-swallow-size: 20MB
  port: 8081
spring:
  config:
    import:
      env.properties
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: live.smtp.mailtrap.io
    port: 2525
    username: api
    password: ${MAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
#    open-in-view: false
    hibernate:
      #      ddl-auto: update
      ddl-auto: update
      show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
jwt:
  secret-key: ${JWTSECRETKEY}
  # 24 Hours
  ttl-ms: 86400000
frontend:
  base-url: http://localhost:4200
